using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Unianio.Genesis
{
    public static class genBone
    {
        public static readonly string[] genesis8roots = {"Genesis8Female" };
        public static readonly string[] bodies = { "Genesis8Female.Shape" };
        public static readonly string[] panties = { "VelocityPants_12751.Shape", "lrpanty_4055.Shape" };
        public static readonly string[] eyelashes = { "Genesis8FemaleEyelashes.Shape" };
        public static readonly string[] bras = { "VelocityBra_6150.Shape", "lrbra_5431.Shape" };

        public const string hip = "hip";
        public const string pelvis = "pelvis";
        public const string head = "head";
        public const string abdomenLower = "abdomenLower";
        public const string abdomenUpper = "abdomenUpper";
        public const string chestLower = "chestLower";
        public const string chestUpper = "chestUpper";
        public const string neckLower = "neckLower";
        public const string neckUpper = "neckUpper";
        public const string tongue01 = "tongue01";
        public const string tongue02 = "tongue02";
        public const string tongue03 = "tongue03";
        public const string tongue04 = "tongue04";
        public const string lCollar = "lCollar";
        public const string lShldrBend = "lShldrBend";
        public const string lShldrTwist = "lShldrTwist";
        public const string lForearmBend = "lForearmBend";
        public const string lForearmTwist = "lForearmTwist";
        public const string lHand = "lHand";
        public const string lCarpal1 = "lCarpal1";
        public const string lIndex1 = "lIndex1";
        public const string lIndex2 = "lIndex2";
        public const string lIndex3 = "lIndex3";
        public const string lCarpal2 = "lCarpal2";
        public const string lMid1 = "lMid1";
        public const string lMid2 = "lMid2";
        public const string lMid3 = "lMid3";
        public const string lCarpal3 = "lCarpal3";
        public const string lRing1 = "lRing1";
        public const string lRing2 = "lRing2";
        public const string lRing3 = "lRing3";
        public const string lCarpal4 = "lCarpal4";
        public const string lPinky1 = "lPinky1";
        public const string lPinky2 = "lPinky2";
        public const string lPinky3 = "lPinky3";
        public const string lThumb1 = "lThumb1";
        public const string lThumb2 = "lThumb2";
        public const string lThumb3 = "lThumb3";
        public const string rCollar = "rCollar";
        public const string rShldrBend = "rShldrBend";
        public const string rShldrTwist = "rShldrTwist";
        public const string rForearmBend = "rForearmBend";
        public const string rForearmTwist = "rForearmTwist";
        public const string rHand = "rHand";
        public const string rCarpal1 = "rCarpal1";
        public const string rIndex1 = "rIndex1";
        public const string rIndex2 = "rIndex2";
        public const string rIndex3 = "rIndex3";
        public const string rCarpal2 = "rCarpal2";
        public const string rMid1 = "rMid1";
        public const string rMid2 = "rMid2";
        public const string rMid3 = "rMid3";
        public const string rCarpal3 = "rCarpal3";
        public const string rRing1 = "rRing1";
        public const string rRing2 = "rRing2";
        public const string rRing3 = "rRing3";
        public const string rCarpal4 = "rCarpal4";
        public const string rPinky1 = "rPinky1";
        public const string rPinky2 = "rPinky2";
        public const string rPinky3 = "rPinky3";
        public const string rThumb1 = "rThumb1";
        public const string rThumb2 = "rThumb2";
        public const string rThumb3 = "rThumb3";
        public const string lEye = "lEye";
        public const string rEye = "rEye";
        public const string lEar = "lEar";
        public const string rEar = "rEar";
        public const string lowerJaw = "lowerJaw";
        public const string lowerFaceRig = "lowerFaceRig";
        public const string lowerTeeth = "lowerTeeth";
        public const string upperTeeth = "upperTeeth";
        public const string upperFaceRig = "upperFaceRig";
        public const string BelowJaw = "BelowJaw";
        public const string Chin = "Chin";
        public const string lCheekLower = "lCheekLower";
        public const string LipBelow = "LipBelow";
        public const string LipLowerMiddle = "LipLowerMiddle";
        public const string lJawClench = "lJawClench";
        public const string lLipCorner = "lLipCorner";
        public const string lLipLowerInner = "lLipLowerInner";
        public const string lLipLowerOuter = "lLipLowerOuter";
        public const string lNasolabialLower = "lNasolabialLower";
        public const string lNasolabialMouthCorner = "lNasolabialMouthCorner";
        public const string rCheekLower = "rCheekLower";
        public const string rJawClench = "rJawClench";
        public const string rLipCorner = "rLipCorner";
        public const string rLipLowerInner = "rLipLowerInner";
        public const string rLipLowerOuter = "rLipLowerOuter";
        public const string rNasolabialLower = "rNasolabialLower";
        public const string rNasolabialMouthCorner = "rNasolabialMouthCorner";
        public const string CenterBrow = "CenterBrow";
        public const string lBrowInner = "lBrowInner";
        public const string lBrowMid = "lBrowMid";
        public const string lBrowOuter = "lBrowOuter";
        public const string lCheekUpper = "lCheekUpper";
        public const string lEyelidInner = "lEyelidInner";
        public const string lEyelidLower = "lEyelidLower";
        public const string lEyelidLowerInner = "lEyelidLowerInner";
        public const string lEyelidLowerOuter = "lEyelidLowerOuter";
        public const string lEyelidOuter = "lEyelidOuter";
        public const string lEyelidUpper = "lEyelidUpper";
        public const string lEyelidUpperInner = "lEyelidUpperInner";
        public const string lEyelidUpperOuter = "lEyelidUpperOuter";
        public const string LipUpperMiddle = "LipUpperMiddle";
        public const string lLipBelowNose = "lLipBelowNose";
        public const string lLipNasolabialCrease = "lLipNasolabialCrease";
        public const string lLipUpperInner = "lLipUpperInner";
        public const string lLipUpperOuter = "lLipUpperOuter";
        public const string lNasolabialMiddle = "lNasolabialMiddle";
        public const string lNasolabialUpper = "lNasolabialUpper";
        public const string lNostril = "lNostril";
        public const string lSquintInner = "lSquintInner";
        public const string lSquintOuter = "lSquintOuter";
        public const string MidNoseBridge = "MidNoseBridge";
        public const string Nose = "Nose";
        public const string rBrowInner = "rBrowInner";
        public const string rBrowMid = "rBrowMid";
        public const string rBrowOuter = "rBrowOuter";
        public const string rCheekUpper = "rCheekUpper";
        public const string rEyelidInner = "rEyelidInner";
        public const string rEyelidLower = "rEyelidLower";
        public const string rEyelidLowerInner = "rEyelidLowerInner";
        public const string rEyelidLowerOuter = "rEyelidLowerOuter";
        public const string rEyelidOuter = "rEyelidOuter";
        public const string rEyelidUpper = "rEyelidUpper";
        public const string rEyelidUpperInner = "rEyelidUpperInner";
        public const string rEyelidUpperOuter = "rEyelidUpperOuter";
        public const string rLipBelowNose = "rLipBelowNose";
        public const string rLipNasolabialCrease = "rLipNasolabialCrease";
        public const string rLipUpperInner = "rLipUpperInner";
        public const string rLipUpperOuter = "rLipUpperOuter";
        public const string rNasolabialMiddle = "rNasolabialMiddle";
        public const string rNasolabialUpper = "rNasolabialUpper";
        public const string rNostril = "rNostril";
        public const string rSquintInner = "rSquintInner";
        public const string rSquintOuter = "rSquintOuter";
        public const string lPectoral = "lPectoral";
        public const string rPectoral = "rPectoral";
        public const string lGluteal = "lGluteal";
        public const string rGluteal = "rGluteal";
        public const string lThighBend = "lThighBend";
        public const string lThighTwist = "lThighTwist";
        public const string lShin = "lShin";
        public const string lFoot = "lFoot";
        public const string lMetatarsals = "lMetatarsals";
        public const string lToe = "lToe";
        public const string lToe_Holder = "lToe_Holder";
        public const string lBigToe = "lBigToe";
        public const string lBigToe_2 = "lBigToe_2";
        public const string lSmallToe1 = "lSmallToe1";
        public const string lSmallToe1_2 = "lSmallToe1_2";
        public const string lSmallToe2 = "lSmallToe2";
        public const string lSmallToe2_2 = "lSmallToe2_2";
        public const string lSmallToe3 = "lSmallToe3";
        public const string lSmallToe3_2 = "lSmallToe3_2";
        public const string lSmallToe4 = "lSmallToe4";
        public const string lSmallToe4_2 = "lSmallToe4_2";
        public const string rThighBend = "rThighBend";
        public const string rThighTwist = "rThighTwist";
        public const string rShin = "rShin";
        public const string rFoot = "rFoot";
        public const string rMetatarsals = "rMetatarsals";
        public const string rToe = "rToe";
        public const string rToe_Holder = "rToe_Holder";
        public const string rBigToe = "rBigToe";
        public const string rBigToe_2 = "rBigToe_2";
        public const string rSmallToe1 = "rSmallToe1";
        public const string rSmallToe1_2 = "rSmallToe1_2";
        public const string rSmallToe2 = "rSmallToe2";
        public const string rSmallToe2_2 = "rSmallToe2_2";
        public const string rSmallToe3 = "rSmallToe3";
        public const string rSmallToe3_2 = "rSmallToe3_2";
        public const string rSmallToe4 = "rSmallToe4";
        public const string rSmallToe4_2 = "rSmallToe4_2";

        public static class attached
        {
            public const string MagicianHat = "MagicianHat";
            public const string HairShort01 = "HairShort01";
            public const string HairPony01 = "HairPony01";
            public const string lRollerBlade = "lRollerBlade";
            public const string rRollerBlade = "rRollerBlade";
            public const string rollerblade_top = "rollerblade_top";
        }

        public static class breasts
        {
            public const string lNipple = "lNipple";
            public const string rNipple = "rNipple";
        }
        public static class OfBen
        {
            public const string Beard1 = "Beard1";
            public const string Beard2 = "Beard2";
            public const string Beard3 = "Beard3";
            public const string cb_LeftShinlShin = "cb_LeftShinlShin";
            public const string cb_RightShinrShin = "cb_RightShinrShin";
        }
    }
}
